# Generated by Django 5.0.4 on 2024-06-27 08:05

import django.db.models.deletion
import medical_claim.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficier', models.CharField(choices=[('Myself', 'Myself'), ('Husband', 'Husband'), ('Children', 'Children')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('file', models.FileField(blank=True, null=True, upload_to=medical_claim.models.user_directory_path)),
                ('claim_year', models.IntegerField(default=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='claim.claim_status')),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approved_Medical_Claim',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medical_claim.medical_claim')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=medical_claim.models.claim_directory_path)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rejected_Medical_Claim',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medical_claim.medical_claim')),
                ('reason', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
