# Generated by Django 5.0.4 on 2024-07-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_alter_claim_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='travel_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
