# Generated by Django 5.0.4 on 2024-06-26 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bank_name', models.CharField(choices=[('Malayan Banking Berhad', 'Malayan Banking Berhad'), ('CIMB Group Holdings', 'CIMB Group Holdings'), ('Public Bank Berhad', 'Public Bank Berhad'), ('RHB Bank', 'RHB Bank'), ('Hong Leong Bank', 'Hong Leong Bank'), ('AmBank', 'AmBank'), ('UOB Malaysia', 'UOB Malaysia'), ('Bank Rakyat', 'Bank Rakyat'), ('OCBC Bank Malaysia', 'OCBC Bank Malaysia'), ('HSBC Bank Malaysia', 'HSBC Bank Malaysia'), ('Bank Islam Malaysia', 'Bank Islam Malaysia'), ('Affin Bank', 'Affin Bank'), ('Alliance Bank Malaysia Berhad', 'Alliance Bank Malaysia Berhad'), ('Standard Chartered Bank Malaysia', 'Standard Chartered Bank Malaysia'), ('MBSB Bank Berhad', 'MBSB Bank Berhad'), ('Citibank Malaysia', 'Citibank Malaysia'), ('Bank Simpanan Nasional (BSN)', 'Bank Simpanan Nasional (BSN)'), ('Bank Muamalat Malaysia Berhad', 'Bank Muamalat Malaysia Berhad'), ('Agrobank', 'Agrobank'), ('Al-Rajhi Malaysia', 'Al-Rajhi Malaysia'), ('Co-op Bank Pertama', 'Co-op Bank Pertama'), ('MBSB Bank', 'MBSB Bank')], max_length=100)),
                ('account_number', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
